EmlVersion: 0.1-alpha
Solution: Register & log in
Contexts:
- Name: Register & log in
  Streams:
  - Stream: User
    Commands:
    - Command:
        Name: Register
        Parameters:
        - Name: email
          Type: string
          Rules: []
        - Name: password
          Type: string
          Rules: []
        - Name: retypedPassword
          Type: string
          Rules: []
        - Name: userId
          Type: string
          Rules:
          - IsRequired
        Preconditions: []
        Postconditions:
        - UserRegistered
        - UserAuthenticated
    Events:
    - Event:
        Name: UserRegistered
        Properties:
        - Name: userId
          Type: string
        - Name: email
          Type: string
        - Name: role
          Type: string
    - Event:
        Name: UserAuthenticated
        Properties:
        - Name: userId
          Type: string
  - Stream: Team
    Commands:
    - Command:
        Name: InviteTeamMember
        Parameters:
        - Name: adminUserId
          Type: string
          Rules:
          - MustExistIn UserLookup
        - Name: emails
          Type: string
          Rules: []
        - Name: teamId
          Type: string
          Rules:
          - IsRequired
        Preconditions: []
        Postconditions:
        - TeamCreated
        - TeamMemberInvited
    - Command:
        Name: AcceptInvitation
        Parameters:
        - Name: userId
          Type: string
          Rules:
          - MustExistIn UserLookup
        - Name: invitationId
          Type: string
          Rules:
          - MustExistIn InvitationLookup
        - Name: teamId
          Type: string
          Rules:
          - IsRequired
        Preconditions: []
        Postconditions:
        - TeamInvitationAccepted
    Events:
    - Event:
        Name: TeamCreated
        Properties:
        - Name: teamId
          Type: string
        - Name: adminUserId
          Type: string
    - Event:
        Name: TeamMemberInvited
        Properties:
        - Name: email
          Type: string
        - Name: invitationId
          Type: string
        - Name: teamId
          Type: string
    - Event:
        Name: TeamInvitationAccepted
        Properties:
        - Name: userId
          Type: string
        - Name: teamId
          Type: string
  Readmodels:
  - Readmodel:
      Name: OutstandingInvitations
      Key: invitationId
      SubscribesTo:
      - TeamMemberInvited
      - UserRegistered
  - Readmodel:
      Name: Team
      Key: teamId
      SubscribesTo:
      - UserRegistered
      - TeamMemberInvited
Errors:
- errorid: NamesMustBeUnique
  context: ""
  stream: ""
  command: ""
  event: ""
  readmodel: ""
  message: 'Names must be unique within a bounded context: ''Team'' found 2 times
    in ''Register & log in''.'
- errorid: MustExistInReadmodelNotFound
  context: Register & log in
  stream: Team
  command: InviteTeamMember
  event: ""
  readmodel: ""
  message: '''InviteTeamMember adminUserId'' has a MustExistIn UserLookup rule, but
    that read model does not exist.'
- errorid: MustExistInReadmodelNotFound
  context: Register & log in
  stream: Team
  command: AcceptInvitation
  event: ""
  readmodel: ""
  message: '''AcceptInvitation userId'' has a MustExistIn UserLookup rule, but that
    read model does not exist.'
- errorid: MustExistInReadmodelNotFound
  context: Register & log in
  stream: Team
  command: AcceptInvitation
  event: ""
  readmodel: ""
  message: '''AcceptInvitation invitationId'' has a MustExistIn InvitationLookup rule,
    but that read model does not exist.'
